### ISSUE TITLE
Add device Screen

### ISSUE THREAD

**Issue by jagathkumar** [muthukumarclay/LynkTest#16]
1) Press button in the center of your Lynk device >> Should be the first screen.

2) bring your Lynk device next to your mobile. >> Should come at the second screen.

**Comment by muthukumarclay** [comment]
No. The user needs to bring the device closer to the phone and then he needs to press it.

**Comment by muthukumarclay** [comment]
Yes you are right. That’s why both of them needs to be on the same page
instead of 2 separate pages. And it is just a place holder so once Giovanni
done with  merging both the pages into one as gif, we will use that.

**Comment by jagathkumar** [comment]
okay then its fine

**Comment by jagathkumar** [comment]
We can open this , close after the UI change.
