### ISSUE TITLE
Duplicate/Same type of Notification during disconnection

### ISSUE THREAD

**Issue by jagathkumar** [muthukumarclay/LynkTest#17]
When the Separation alert is ON >> the "you forgot your ###" can be eliminated from that , and that can be replaced as for the global notification instead of "disconnected from ###".So No need a separate notification for it, phone ringtone tone alone is good.

**Comment by muthukumarclay** [comment]
There are 2 types of notification being generated during device disconnection `You forgot your ###` and `Disconnected from ####`. 

`Disconnected from ####` is too technical and both of the notification mean same thing. So remove the notification `Disconnected from ####`. 

@jagathkumar

**Comment by jagathkumar** [comment]
its verified 

verified result: "You forgot your ###" pop-up notification will be generated, when the device disconnect with the phone, when the phone app in Back ground or in terminated states. only on the condition when the separation alert is toggled "ON" ,and silent mode toggled "OFF".
