### ISSUE TITLE
Lynk Device got Disconnected

### ISSUE THREAD

**Issue by muthukumarclay** [muthukumarclay/LynkTest#2]
I need to give minimum 1 sec duration between start buzz and stop buzz. if not, devices gets disconnected automatically.

**Comment by muthukumarclay** [comment]
@jagathkumar

**Comment by jagathkumar** [comment]
yes have to , the connection interval is 1100ms = 1.1 S , the command gap between command should maintain >1s

**Comment by muthukumarclay** [comment]
Thanks @jagathkumar. Fixed it.
