### ISSUE TITLE
Logout Logic

### ISSUE THREAD

**Issue by muthukumarclay** [muthukumarclay/LynkTest#8]
All the unsaved data is monitored by the app like temp device. So before logout inform the user about not saving the data and if he choose to logout data will be lost.

**Comment by muthukumarclay** [comment]
Since informing user about technical details like `Data saved locally` might confuse the user. So the data automatically saved locally without informing the user. And the data will be synced with the server automatically whenever the internet is available.

You need internet connection to logout, change use profile image,  change password and delete device.

**Comment by jagathkumar** [comment]
when logout all the device information vanished, its not retrieved from the server.

**Comment by jagathkumar** [comment]
open this issue.

**Comment by jagathkumar** [comment]
Device information retrieved on Log out and log in back again. its verified.
