### ISSUE TITLE
API to check for Separation Alert status on the Device

### ISSUE THREAD

**Issue by muthukumarclay** [muthukumarclay/LynkTest#9]
We need an API on the device side to check the separation alert status on the device like `requestSeparationAlertStatus`

**Comment by muthukumarclay** [comment]
@jegathkumar please let me know once the new firmware is ready with the above API.

**Comment by jagathkumar** [comment]
@muthukumarclay : Once its done i share the OTA image of it. May be by end of the week.

**Comment by jagathkumar** [comment]
After this feature added in FW 2.5.0 , device connect and disconnect happens in a sequence manner in the app FG, BG and termination states.

**Comment by jagathkumar** [comment]
open this issue.

**Comment by jagathkumar** [comment]
now its stable with 2.5.0 Firmware.  its verified

**Comment by jagathkumar** [comment]
so should i remove up "Separation Alert status on the Device
" this feature from the device side.

**Comment by muthukumarclay** [comment]
No. We need that. Let it be.

**Comment by jagathkumar** [comment]
okay.
